name: .NET Core Console application

on:
  push:
    branches: [ develop, master ]
    paths:
      - 'csharp'
      - '.github/workflows/dotnet-desktop.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./csharp
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x  

    - name: Restore
      run: | 
        cd csharp
        dotnet restore
 
    - name: Build
      run: |
        cd csharp
        dotnet build --configuration Release --no-restore
 
    - name: Test
      run: | 
        cd csharp/
        dotnet test --no-restore
  Runapp: 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - name: RunApp
      run: |
        cd csharp/csprogram
        dotnet run